language: node_js
node_js:
- '6'
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.12.0
branches:
  only:
  - dev
services:
- mongodb
cache:
  directories:
  - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - ruby2.2
before_script:
- npm install -g gulp-cli node-gyp
after_success:
- bash ./travis/after_success.sh
