language: node_js
node_js:
- '6.9.4'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: 6.9.4
branches:
  only:
  - dev
services:
- mongodb
cache:
  directories:
  - node_modules
  - client/bower_components
before_script:
- npm install
- bower install
after_success:
- bash ./travis/after_success.sh
